import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Menu } from "@/components/common/menu";
import { TelegramProvider } from "@/hooks/useTelegram";
import { UserProvider } from "@/hooks/useUser";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<Script src="https://telegram.org/js/telegram-web-app.js?59" strategy="beforeInteractive" />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
				style={{
					paddingTop: "var(--tg-content-safe-area-inset-top)",
					paddingBottom: "env(safe-area-inset-bottom, 0px)",
					paddingLeft: "env(safe-area-inset-left, 0px)",
					paddingRight: "env(safe-area-inset-right, 0px)"
				}}
			>
				<TelegramProvider>
					<UserProvider>
						{children}
						<div className="flex justify-center">
							<Menu />
						</div>
					</UserProvider>
				</TelegramProvider>
			</body>
		</html>
	);
}
